"""The Publications page: the papers this website is built on, and how to cite it.

Pure data; edit the lists.  Every entry is one card on `site/publications/`, grouped by
`group` in the order of GROUPS.  `used` is the one line saying where the paper enters the
site: a cost table, a rule, a fidelity, a model.  `arxiv` and `doi` become links; `url`
is for anything else (with an optional `url_label`).  A paper written about the project
itself belongs in the group `this`; until there is one the page cites the software.
"""

from __future__ import annotations

GROUPS = (
    ("this", "From this project", "Papers about the tool and the studies run with it."),
    ("arch", "Architectures and cost tables",
     "The QCCD architecture studies whose cost tables, devices and results the leaderboard's tasks are measured against."),
    ("control", "Wiring and control",
     "Why the control plane is broadcast, and what a compiler for a broadcast-wired machine has to respect."),
    ("transport", "Transport, heating and junctions",
     "What moving an ion costs in time and quanta, and what happens at a junction."),
    ("hardware", "Processors and electrode design",
     "The measured processor the gate numbers come from, and the electrode model the fab view is checked against."),
    ("codes", "Codes and the QCCD proposal",
     "The code the tasks run a round of, and the paper that proposed the architecture."),
)

PUBS: list[dict] = [
    # ---------------------------------------------------------------- architectures
    {"key": "jones2026", "group": "arch",
     "title": "Architecting Scalable Trapped Ion Quantum Computers using Surface Codes",
     "authors": ["Scott Jones", "Prakash Murali"],
     "venue": "ASPLOS 2026", "year": 2026, "arxiv": "2510.23519", "doi": "10.1145/3779212.3790128",
     "used": "the qccdsim_jones cost table the leaderboard ranks by; the species and coherence time; rules R7c and R16."},
    {"key": "khan2025", "group": "arch",
     "title": "Cyclone: Designing Efficient and Highly Parallel QCCD Architectural Codesigns for Fault Tolerant Quantum Memory",
     "authors": ["Sahil Khan", "Abhinav Anand", "Kenneth R. Brown", "Jonathan M. Baker"],
     "venue": "arXiv preprint", "year": 2025, "arxiv": "2511.15910",
     "used": "rigid rotation of a ring of ions as one instruction, the cyclone cost table, and the ring-plus-docks family; rules R7 and R13."},
    {"key": "murali2020", "group": "arch",
     "title": "Architecting Noisy Intermediate-Scale Trapped Ion Quantum Computers",
     "authors": ["Prakash Murali", "Dripto M. Debroy", "Kenneth R. Brown", "Margaret Martonosi"],
     "venue": "ISCA 2020", "year": 2020, "arxiv": "2004.04706",
     "used": "the chain-length term of the two-qubit gate error (calibration G1); the baseline grid with static scheduling."},
    {"key": "tham2026", "group": "arch",
     "title": "Breakeven demonstration of quantum low-density parity-check codes",
     "authors": ["Edwin Tham", "Michael L. Goldman", "Shantanu Debnath", "Ashay N. Patel", "Jyothi Saraladevi",
                 "Jason Nguyen", "Erik Nielsen", "Neal Pisenti", "Kenneth Wright", "John Gamble", "Nicolas Delfos", "et al."],
     "venue": "arXiv preprint", "year": 2026, "arxiv": "2606.06455",
     "used": "the stationary chain with in-place mid-circuit measurement; global Doppler cooling as the cool primitive (rule R7c)."},
    {"key": "ovide2024", "group": "arch",
     "title": "Scaling and assigning resources on ion trap QCCD architectures",
     "authors": ["Anabel Ovide", "Daniele Cuomo", "Carmen G. Almudever"],
     "venue": "arXiv preprint", "year": 2024, "arxiv": "2408.00225",
     "used": "resource assignment on QCCD grids, one of the studies the evaluation is compared against."},
    # ---------------------------------------------------------------- wiring and control
    {"key": "malinowski2023", "group": "control",
     "title": "How to wire a 1000-qubit trapped ion quantum computer",
     "authors": ["M. Malinowski", "D. T. C. Allcock", "C. J. Ballance"],
     "venue": "PRX Quantum 4, 040313", "year": 2023, "arxiv": "2305.12773", "doi": "10.1103/PRXQuantum.4.040313",
     "used": "WISE broadcast wiring: about a hundred DACs regardless of size, one movement class per cycle (rule R4)."},
    {"key": "ruan2025", "group": "control",
     "title": "TrapSIMD: SIMD-Aware Compiler Optimization for 2D Trapped-Ion Quantum Machines",
     "authors": ["Jixuan Ruan", "Hezi Zhang", "Xiang Fang", "Ang Li", "Wesley C. Campbell", "Eric Hudson", "David Hayes",
                 "Hartmut Haeffner", "Travis Humble", "Jens Palsberg", "Yufei Ding"],
     "venue": "arXiv preprint", "year": 2025, "arxiv": "2504.17886",
     "used": "the SIMD movement classes of the control plane, and the per-gate-zone thermal duty cycle (rule R7b)."},
    # ---------------------------------------------------------------- transport and heating
    {"key": "kaushal2020", "group": "transport",
     "title": "Shuttling-Based Trapped-Ion Quantum Information Processing",
     "authors": ["V. Kaushal", "B. Lekitsch", "A. Stahl", "J. Hilder", "D. Pijn", "C. Schmiegelow", "A. Bermudez",
                 "M. Müller", "F. Schmidt-Kaler", "U. Poschinger"],
     "venue": "AVS Quantum Science 2, 014101", "year": 2020, "arxiv": "1912.04712",
     "used": "the vocabulary of transport primitives: linear transport, separation and merging, swap by crystal rotation."},
    {"key": "munoz2026", "group": "transport",
     "title": "A framework for the benchmarking of transport-induced excitations in shuttling-based ion-trap quantum processors",
     "authors": ["Rodrigo Munoz", "Phil Nuschke", "Teresa Meiners", "Brigitte Kaune", "Christian Ospelkaus"],
     "venue": "arXiv preprint", "year": 2026, "arxiv": "2605.25118",
     "used": "the transport_excitation curves and their fast and slow operating points; the anomalous heating rate; rules R15 and R17."},
    {"key": "sterk2022", "group": "transport",
     "title": "Closed-loop optimization of fast trapped-ion shuttling with sub-quanta excitation",
     "authors": ["Jonathan D. Sterk", "Henry Coakley", "Joshua Goldberg", "Vincent Hietala", "Jason Lechtenberg",
                 "Hayden McGuinness", "Daniel McMurtrey", "L. Paul Parazzoli", "Jay Van Der Wall", "Daniel Stick"],
     "venue": "npj Quantum Information 8, 68", "year": 2022, "arxiv": "2201.07358", "doi": "10.1038/s41534-022-00579-3",
     "used": "sub-quanta transport is achievable with shaped waveforms; the channel count of a real controller."},
    {"key": "wright2013", "group": "transport",
     "title": "Reliable transport through a microfabricated X-junction surface-electrode ion trap",
     "authors": ["Kenneth Wright", "Jason M. Amini", "Daniel L. Faircloth", "Curtis Volin", "S. Charles Doret", "Harley Hayden",
                 "C.-S. Pai", "David W. Landgren", "Douglas Denison", "Tyler Killian", "Richart E. Slusher", "Alexa W. Harter"],
     "venue": "New Journal of Physics 15, 033004", "year": 2013, "arxiv": "1210.3655", "doi": "10.1088/1367-2630/15/3/033004",
     "used": "the measured junction crossing and the roughly 85 uncooled round trips before an ion is lost; rule R18."},
    {"key": "hucul2008", "group": "transport",
     "title": "On the Transport of Atomic Ions in Linear and Multidimensional Ion Trap Arrays",
     "authors": ["D. Hucul", "M. Yeo", "W. K. Hensinger", "J. Rabchuk", "S. Olmschenk", "C. Monroe"],
     "venue": "Quantum Information and Computation 8, 501", "year": 2008, "arxiv": "quant-ph/0702175",
     "used": "the RF barriers on the approaches to a junction, and why a bend is not a junction (rule R18)."},
    {"key": "brownnutt2015", "group": "transport",
     "title": "Ion-trap measurements of electric-field noise near surfaces",
     "authors": ["M. Brownnutt", "M. Kumph", "P. Rabl", "R. Blatt"],
     "venue": "Reviews of Modern Physics 87, 1419", "year": 2015, "arxiv": "1409.6572", "doi": "10.1103/RevModPhys.87.1419",
     "used": "anomalous heating: the heating-rate formula and the survey of measured rates."},
    {"key": "sedlacek2018", "group": "transport",
     "title": "Distance scaling of electric-field noise in a surface-electrode ion trap",
     "authors": ["J. A. Sedlacek", "A. Greene", "J. Stuart", "R. McConnell", "C. D. Bruzewicz", "J. M. Sage", "J. Chiaverini"],
     "venue": "Physical Review A 97, 020302", "year": 2018, "arxiv": "1712.00188", "doi": "10.1103/PhysRevA.97.020302",
     "used": "the inverse-fourth-power distance scaling of field noise, and the cryogenic reduction."},
    # ---------------------------------------------------------------- processors and electrodes
    {"key": "moses2023", "group": "hardware",
     "title": "A Race Track Trapped-Ion Quantum Processor",
     "authors": ["S. A. Moses", "C. H. Baldwin", "M. S. Allman", "R. Ancona", "L. Ascarrunz", "C. Barnes", "J. Bartolotta",
                 "B. Bjork", "P. Blanchard", "M. Bohn", "J. G. Bohnet", "N. C. Brown", "et al."],
     "venue": "Physical Review X 13, 041052", "year": 2023, "arxiv": "2305.03828", "doi": "10.1103/PhysRevX.13.041052",
     "used": "the two-qubit, single-qubit and measurement fidelities and times of the default document; the racetrack and its conveyor-belt rotation."},
    {"key": "zhang2022", "group": "hardware",
     "title": "Optimization and implementation of a surface-electrode ion trap junction",
     "authors": ["Chi Zhang", "Karan K. Mehta", "Jonathan P. Home"],
     "venue": "New Journal of Physics 24, 073030", "year": 2022, "arxiv": "2201.12579", "doi": "10.1088/1367-2630/ac7db6",
     "used": "the gapless electrode model and its tolerances; the junction the field solver reproduces to within 3%."},
    {"key": "wesenberg2008", "group": "hardware",
     "title": "Electrostatics of surface-electrode ion traps",
     "authors": ["Janus H. Wesenberg"],
     "venue": "Physical Review A 78, 063410", "year": 2008, "arxiv": "0808.1623", "doi": "10.1103/PhysRevA.78.063410",
     "used": "the solid-angle potential of a planar electrode, and the conditions under which the model holds."},
    {"key": "house2008", "group": "hardware",
     "title": "Analytic model for electrostatic fields in surface-electrode ion traps",
     "authors": ["M. G. House"],
     "venue": "Physical Review A 78, 033402", "year": 2008, "doi": "10.1103/PhysRevA.78.033402",
     "used": "the companion analytic treatment of the planar electrode potential."},
    {"key": "revelle2020", "group": "hardware",
     "title": "Phoenix and Peregrine Ion Traps",
     "authors": ["Melissa C. Revelle"],
     "venue": "arXiv preprint", "year": 2020, "arxiv": "2009.02398",
     "used": "published ion heights of shipped traps, against which the solved heights are compared."},
    # ---------------------------------------------------------------- codes and the proposal
    {"key": "bravyi2024", "group": "codes",
     "title": "High-threshold and low-overhead fault-tolerant quantum memory",
     "authors": ["Sergey Bravyi", "Andrew W. Cross", "Jay M. Gambetta", "Dmitri Maslov", "Patrick Rall", "Theodore J. Yoder"],
     "venue": "Nature 627, 778", "year": 2024, "arxiv": "2308.07915", "doi": "10.1038/s41586-024-07107-7",
     "used": "the [[144,12,12]] gross code, its seven-stage syndrome cycle and its threshold of about 0.7%."},
    {"key": "kielpinski2002", "group": "codes",
     "title": "Architecture for a large-scale ion-trap quantum computer",
     "authors": ["D. Kielpinski", "C. Monroe", "D. J. Wineland"],
     "venue": "Nature 417, 709", "year": 2002, "doi": "10.1038/nature00784",
     "used": "the QCCD proposal: many small traps, ions shuttled between them, sympathetic cooling by a second species."},
]

#: How to cite the website and the tool while no paper about them is published.
SOFTWARE = {
    "note": "No paper about the tool has been published yet. Until there is one, cite the software and the website.",
    "bibtex": """@software{qccd,
  author = {Ye, Zhuoyang},
  title  = {QCCD: a fault-tolerant algorithm and trapped-ion architecture codesign tool},
  year   = {2026},
  url    = {https://github.com/yezhuoyang/QCCD},
  note   = {https://qccd.academy/}
}""",
}
