"""Run a compiler over a suite and score it: `run_suite(suite, compiler) -> qccd.compiler_report`.

The same function grades locally (`qccd bench run`) and on the official server (the grader,
with the hidden split); only the runner that starts the compiler differs:

  local     `contract.invoke`: a limited child process of this one
  official  `SpoolRunner`: the grader hands each pair to a separate sandbox container that
            holds no secrets and cannot see the grader's files (qccd.bench.sandbox)

SCORING (the manifest's metrics; the suite's `rank_by` is `speedup`):

  per pair     valid | wrong | refused | timeout | crash | no_output | not_run
  coverage     valid pairs / pairs
  speedup      geometric mean, over pairs BOTH this compiler and the reference compiled validly,
               of T_jones(reference) / T_jones(this): above 1 is faster than qccdc
  ler_ratio    geometric mean, over memory pairs both compiled, of LER(this) / LER(reference),
               with LER smoothed as (errors + 0.5) / (shots + 1) so a zero-error run still counts
  wrong        any wrong pair makes the entry ineligible: a compiler that emits a program that
               breaks the machine or computes something else is worse than one that says no
"""

from __future__ import annotations

import json
import os
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any, Callable, Mapping

from .check import geomean, grade_pair
from .contract import CompilerSpec, Invocation, build, invoke
from .suite import Pair, Suite

__all__ = ["run_suite", "reference_compiler", "REPORT_KIND", "STATUSES", "summarize", "LocalRunner",
           "reference_results"]

REPORT_KIND = "qccd.compiler_report"
STATUSES = ("valid", "wrong", "refused", "timeout", "crash", "no_output", "not_run", "cancelled")
REPO = Path(__file__).resolve().parents[2]


def reference_compiler() -> CompilerSpec:
    """qccdc + cooling, as a contract compiler (qccd.bench.baseline)."""
    return CompilerSpec(root=Path(__file__).resolve().parent, name="qccdc (reference)", runtime="python3",
                        entry=("python3", "-m", "qccd.bench.baseline"), build=None,
                        about="the reference compiler: qccdc rotation or routing, then cooling")


def _expand(device_doc: Mapping, dest: Path) -> tuple[Path, Path]:
    """device.arch.json and device.expanded.json for one device (cached per directory)."""
    import subprocess
    import sys
    dev, ex = dest / "device.arch.json", dest / "device.expanded.json"
    if not ex.exists():
        dest.mkdir(parents=True, exist_ok=True)
        dev.write_text(json.dumps(device_doc), encoding="utf-8")
        r = subprocess.run([sys.executable, str(REPO / "Compiler" / "bridge" / "export_arch.py"), str(dev),
                            "-o", str(ex)], capture_output=True, text=True, timeout=300)
        if r.returncode != 0:
            raise RuntimeError(f"export_arch failed: {(r.stderr or r.stdout)[-500:]}")
    return dev, ex


class LocalRunner:
    """Runs the compiler as a limited child of this process (`qccd bench run`, tests, a dev server)."""

    def build(self, spec: CompilerSpec, *, workdir: Path, timeout: float, cancel=None) -> tuple[bool, str]:
        return build(spec, workdir=workdir, timeout=timeout, cancel=cancel)

    def invoke(self, spec: CompilerSpec, circuit: Path, device: Path, expanded: Path, out: Path, *,
               timeout: float, mem_mb: int, cancel=None) -> Invocation:
        return invoke(spec, circuit, device, expanded, out, timeout=timeout, mem_mb=mem_mb, cancel=cancel)


def run_suite(suite: Suite, compiler: CompilerSpec, *, workdir: Path, split: str = "public",
              hidden_seed: str | None = None, only: list[str] | None = None, jobs: int = 1,
              profile: str = "local", runner: Any = None, extra_pairs: list[Pair] | None = None,
              reference: Mapping | None = None,
              progress: Callable[[int, int, str, str], None] | None = None,
              cancel: threading.Event | None = None) -> dict[str, Any]:
    """Build the compiler once, run it on every pair, grade each output, score against the
    reference.  Never raises for the compiler's faults: they are in the report.

    `extra_pairs` are graded after the suite's own (the official grader passes the hidden split
    here, generated by the worker so the grader never holds its seed)."""
    started = time.time()
    work = Path(workdir)
    work.mkdir(parents=True, exist_ok=True)
    limits = dict(suite.manifest.get("limits") or {})
    ler = dict(suite.manifest.get("ler") or {})
    physics_ref = dict(suite.manifest.get("physics") or {})
    pairs = (suite.pairs(split, hidden_seed=hidden_seed, only=only) if split != "none" else []) + list(extra_pairs or [])
    runner = runner or LocalRunner()
    ok_build, build_log = runner.build(compiler, workdir=work, timeout=float(limits.get("build_timeout_s", 600)),
                                       cancel=cancel)
    results: dict[str, dict] = {}
    deadline = started + float(limits.get("suite_timeout_s", 7200))
    lock = threading.Lock()
    # Compilers run in parallel (child processes); their outputs are graded ONE AT A TIME.  Two
    # threads inside stim at once deadlocked (2026-09-28: `reference_sample` in both, one waiting
    # on an import its C++ side started), and grading is Python-bound, so parallel grading bought
    # nothing anyway.
    grading = threading.Lock()
    done = [0]

    def one(pair: Pair) -> dict:
        rec: dict[str, Any] = {**pair.to_json(), "status": "not_run", "reason": "", "seconds": 0.0}
        if not ok_build:
            rec.update(status="crash", reason="the build step failed")
            return rec
        if cancel is not None and cancel.is_set():
            rec.update(status="cancelled", reason="the run was cancelled")
            return rec
        if time.time() > deadline:
            rec.update(reason="the suite's time budget ran out before this pair")
            return rec
        pdir = work / "pairs" / pair.id.replace("/", "_")
        pdir.mkdir(parents=True, exist_ok=True)
        circuit = pdir / "circuit.qasm"
        circuit.write_text(pair.qasm, encoding="utf-8")
        dev, ex = _expand(pair.device_doc, work / "devices" / pair.device)
        inv = runner.invoke(compiler, circuit, dev, ex, pdir / "out", timeout=float(limits.get("pair_timeout_s", 120)),
                            mem_mb=int(limits.get("pair_mem_mb", 4096)), cancel=cancel)
        rec["seconds"] = round(inv.seconds, 3)
        rec["certificate"] = inv.certificate is not None
        if inv.status != "ok":
            rec.update(status=inv.status, reason=_first_line(inv.log) or inv.status)
            return rec
        with grading:
            g = grade_pair(pair, inv.program, physics=physics_ref, ler=ler, limits=limits, workdir=pdir)
        rec.update(g)
        return rec

    def tracked(pair: Pair) -> dict:
        rec = one(pair)
        with lock:
            results[pair.id] = rec
            done[0] += 1
            if progress:
                progress(done[0], len(pairs), pair.id, rec["status"])
        return rec

    if jobs > 1:
        with ThreadPoolExecutor(max_workers=jobs, thread_name_prefix="qccd-bench") as ex:
            list(ex.map(tracked, pairs))
    else:
        for p in pairs:
            tracked(p)
    ordered = [results[p.id] for p in pairs]
    ref = dict(reference) if reference is not None else suite.baseline()
    return _report(suite, compiler, ordered, ref, split=split, profile=profile, started=started,
                   build={"ok": ok_build, "log": build_log[-2000:]})


def _first_line(log: str) -> str:
    lines = [ln.strip() for ln in (log or "").splitlines() if ln.strip()]
    return lines[-1][:300] if lines else ""


def _smoothed(l: Mapping | None) -> float | None:
    if not l or l.get("shots") is None:
        return None
    return (float(l.get("errors") or 0) + 0.5) / (float(l["shots"]) + 1.0)


def summarize(pairs: list[dict], reference: Mapping) -> dict[str, Any]:
    """The suite-level numbers from per-pair records and the reference's."""
    counts = {s: 0 for s in STATUSES}
    for r in pairs:
        counts[r["status"]] = counts.get(r["status"], 0) + 1
    ratios, lers, compared = [], [], []
    for r in pairs:
        base = reference.get(r["id"]) or {}
        r["reference"] = {"status": base.get("status"), "T_jones": (base.get("metrics") or {}).get("T_jones"),
                          "ler": (base.get("ler") or {}).get("ler")}
        if r["status"] != "valid" or base.get("status") != "valid":
            continue
        t_you, t_ref = (r.get("metrics") or {}).get("T_jones"), (base.get("metrics") or {}).get("T_jones")
        if t_you and t_ref:
            ratios.append(t_ref / t_you)
            r["speedup"] = t_ref / t_you
            compared.append(r["id"])
        a, b = _smoothed(r.get("ler")), _smoothed(base.get("ler"))
        if a and b:
            lers.append(a / b)
            r["ler_ratio"] = a / b
    n = len(pairs)
    return {"counts": counts, "pairs": n, "hidden_pairs": sum(1 for r in pairs if r.get("split") == "hidden"),
            "compared": len(compared),
            "coverage": (counts["valid"] / n) if n else 0.0, "speedup": geomean(ratios),
            "ler_ratio": geomean(lers), "wrong": counts["wrong"],
            "compile_seconds": round(sum(float(r.get("seconds") or 0) for r in pairs), 3)}


def _report(suite: Suite, compiler: CompilerSpec, pairs: list[dict], reference: Mapping, *, split: str,
            profile: str, started: float, build: Mapping) -> dict[str, Any]:
    from ..workspace import evaluator_identity
    s = summarize(pairs, reference)
    spec = {m["name"]: m for m in suite.manifest.get("metrics") or []}
    rank_by = suite.manifest.get("rank_by", "speedup")
    metrics = {k: {"value": s[k], "unit": spec.get(k, {}).get("unit", ""), "better": spec.get(k, {}).get("better"),
                   "ranked": k == rank_by} for k in ("speedup", "coverage", "ler_ratio", "wrong", "compile_seconds")}
    reasons = []
    if not build.get("ok"):
        reasons.append("the build step failed")
    if s["wrong"]:
        reasons.append(f"{s['wrong']} pair(s) wrong: a program broke a rule or computes something else")
    if s["counts"]["valid"] == 0:
        reasons.append("no pair compiled validly")
    if s["speedup"] is None:
        reasons.append("no pair to compare with the reference compiler")
    if profile != "official":
        reasons.insert(0, f"profile {profile!r}: only the official grader's report can be ranked")
    eligible = not reasons
    return {
        "kind": REPORT_KIND, "version": 1,
        "suite": {"id": suite.id, "digest": suite.digest, "title": suite.title},
        "compiler": {"name": compiler.name, "about": compiler.about, "runtime": compiler.runtime,
                     "digest": compiler.digest() if (compiler.root / "qccd-compiler.json").exists() else "reference"},
        "evaluator": evaluator_identity(), "profile": profile, "split": split, "build": dict(build),
        "summary": s, "metrics": metrics, "rank_by": rank_by,
        "eligibility": {"eligible": eligible, "policy": "no wrong pair, at least one valid pair compared with "
                        "the reference, graded by the official grader", "reasons": reasons},
        "pairs": pairs,
        "timing": {"started_at": started, "finished_at": time.time(), "wall_seconds": round(time.time() - started, 3)},
    }


def reference_results(suite: Suite, pairs: list[Pair], *, workdir: Path) -> dict[str, dict]:
    """The reference compiler's graded results on `pairs` (the hidden split has no pinned
    baseline: the grader measures the reference on it, in-process, before the entry)."""
    if not pairs:
        return {}
    rep = run_suite(suite, reference_compiler(), workdir=workdir, split="none", extra_pairs=pairs, reference={})
    return {r["id"]: {k: r.get(k) for k in ("status", "reason", "seconds", "metrics", "ler")} for r in rep["pairs"]}
