"""The agent interface: what an agent may do on a page is what the code declares, nothing else.

THE RULE.  Anything a person can do on a QCCD page, an agent can find, read and do through a
declared interface; anything that is not declared, the agent cannot do -- its page tools refuse
it and say what is declared instead.  Every declaration lives in code and is read when the
page is served, so a rebuild changes what agents know with nothing to update by hand.
`tests/test_agent_interface.py` refuses a change that adds UI without its declaration.
(docs/agent-interface.md is the developer's version of this.)

Four kinds of thing are declared:

* PLACES -- where `navigate` may go: the site's own page index (generated by the site build,
  every page carries it) and the workspace's pages.  A link that is ON the page may be
  followed too: the page's author put it there.  A path that is neither is a guess, and is
  refused with the nearest real places.
* CONTROLS -- what `click`, `fill` and `press` may operate:
    - an element with `data-hint="<key>"` whose key the page describes (the Studio's explain
      layer, `EDITOR.hintFor`; a site page's own `window.QCCD_HINTS`) -- the inline way, and
      the only way for anything new;
    - a link, and a native fold-out (`<summary>`), which say what they do by being what they are;
    - a field or button inside a DECLARED FORM (a region the code generates from a schema,
      declared once as a whole);
    - an OUT-OF-LINE declaration in `OUT_OF_LINE` below, for controls on pages that cannot be
      edited right now without regenerating the whole site (the Studio's files are stamped
      into every page).  This list may only shrink: the test pins its length.
* VERBS -- the Studio's API (`window.EDITOR`), declared function by function in
  `qccd/viz/js/editor_api.json`; an agent's `studio` action calls only verbs declared for
  agents; on the person's own workspace Studio what a design verb draws is committed as the
  agent's change set (the page syncs it with `by_page_action`), and only the course's verbs,
  which would replace the design with a lesson's, stay off.
* ACTIONS and TOOLS -- the page actions (`service.PAGE_ACTIONS`, implemented in web/pageact.js)
  and the MCP tools (`mcp_server._tools`), declared by the code that serves them.

`manifest()` is all of it as one document: `qccd_read_reference(section='interface')`.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

__all__ = ["OUT_OF_LINE", "DECLARED_FORMS", "editor_api", "api_keys", "page_contract", "manifest", "places"]

_REPO_PKG = Path(__file__).resolve().parents[1]
EDITOR_JS = _REPO_PKG / "viz" / "js" / "editor.js"
EDITOR_API = _REPO_PKG / "viz" / "js" / "editor_api.json"

#: regions the code GENERATES controls into from a schema or a table; a field or button inside
#: one is declared by the region (its own label says which field it is).  Selector -> what.
DECLARED_FORMS = {
    "#palStart": "the Start panel: pick a generator card (chain, ring, grid, ...), a shipped device, or a blank "
                 "canvas, optionally named first; each card says what it makes",
    "#stageEmpty": "the empty canvas's Start cards (the same generators, shipped devices and blank canvas as the "
                   "Start panel)",
    "#palElements": "the rail's forms, generated from the schema: Append a row, Machine settings (primitives, "
                    "heating, species, control, budgets), Components -- each field is labelled with the schema "
                    "field it writes, and its row's button applies it",
}

#: controls declared outside their page's code: selector -> {name, does}.  ONLY for controls on
#: pages that cannot be changed now without regenerating every site page (the Studio's
#: template and scripts are stamped into each one).  Move an entry inline -- `data-hint` plus
#: a HINTS entry -- at the next regeneration and delete it here.  This list may only shrink:
#: tests/test_agent_interface.py pins its length, so a NEW control must be declared inline.
OUT_OF_LINE = {
    # the Studio (qccd/viz: render.py's template and js/editor.js, stamped into every site page)
    "#lnPrev": {"on": "studio", "name": "Previous lesson", "does": "open the lesson before this one"},
    "#pChip": {"on": "studio", "name": "Programme chip",
               "does": "shows which programme the Program pane lists; press it to switch"},
    "#qFollow": {"on": "studio", "name": "Follow (circuit)",
                 "does": "keep the executing circuit statement scrolled into view"},
    "#aFilter": {"on": "studio", "name": "Filter (device)", "does": "show only the device rows containing this text"},
    "#eSrc": {"on": "studio", "name": "Device source",
              "does": "the device as its builder program; edit it and the picture follows"},
    "#eWhich": {"on": "studio", "name": "Source language", "does": "which listing the Device panel shows (Python, ...)"},
    "#eCopy": {"on": "studio", "name": "Copy", "does": "copy the listing to the clipboard"},
    "#eOut": {"on": "studio", "name": "Edited device", "does": "the edited architecture, ready to save as a file"},
    "#pwDrive": {"on": "studio", "name": "Test drive",
                 "does": "write the smallest programme that exercises this device and play it"},
    "#pwText": {"on": "studio", "name": "Write panel text",
                "does": "a test programme in the Write language (p.init, p.shuttle, p.gate, ...); press Evaluate "
                        "to price, check and play it"},
}
OUT_OF_LINE_MAX = len(OUT_OF_LINE)

#: the workspace's own pages (always places)
WORKSPACE_PLACES = [
    {"url": "/studio", "title": "Your Studio", "about": "the person's own live design (their Design page)"},
    {"url": "/trace", "title": "Agent traces", "about": "what each agent did for each request, to replay"},
    {"url": "/runview/<run_id>", "title": "A run", "about": "a run's own page: its device, program and animation"},
    {"url": "/compare?runs=<a>,<b>", "title": "Side by side", "about": "two runs on one clock"},
]


def api_keys(src: str) -> list:
    """The top-level keys of `var API = {...}` in editor.js (nested bodies and strings skipped)."""
    a = src.index("var API = {")
    i = a + len("var API = {")
    depth, keys = 1, []
    in_str, esc, line_comment, block_comment, at_key = None, False, False, False, True
    while depth > 0:
        c = src[i]
        nxt = src[i + 1] if i + 1 < len(src) else ""
        if line_comment:
            line_comment = c != "\n"
        elif block_comment:
            if c == "*" and nxt == "/":
                block_comment = False
                i += 1
        elif in_str:
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == in_str:
                in_str = None
        elif c == "/" and nxt == "/":
            line_comment = True
        elif c == "/" and nxt == "*":
            block_comment = True
        elif c in "'\"`":
            in_str = c
        elif c in "{([":
            depth += 1
        elif c in "})]":
            depth -= 1
        elif depth == 1:
            if at_key:
                m = re.match(r"\s*([A-Za-z_$][\w$]*)\s*:", src[i:])
                if m:
                    keys.append(m.group(1))
                    i += m.end()
                    at_key = False
                    continue
            if c == ",":
                at_key = True
        i += 1
    return keys


def editor_api() -> dict:
    return json.loads(EDITOR_API.read_text(encoding="utf-8"))["verbs"]


def places(site_index: list | None) -> list:
    """Every place `navigate` may go on the website: the index's pages (their paths, each once)."""
    seen, out = set(), []
    for e in site_index or []:
        path = "/web/" + str(e.get("u") or "").split("#")[0].lstrip("/")
        if path not in seen:
            seen.add(path)
            out.append(path)
    return out


def page_contract(*, site_index: list | None = None, design_page: bool = False, aliases: list | None = None) -> dict:
    """What a page's tools enforce (web/pageact.js reads it as window.QCCD_INTERFACE)."""
    verbs = {k: {"kind": v["kind"], "does": v["does"], **({"args": v["args"]} if v.get("args") else {})}
             for k, v in editor_api().items() if v["use"] == "agent"}
    return {"verbs": verbs, "not_for_agents": {k: v["use"] for k, v in editor_api().items() if v["use"] != "agent"},
            "forms": DECLARED_FORMS, "controls": {k: v for k, v in OUT_OF_LINE.items()},
            "places": places(site_index) if site_index else None, "aliases": aliases or [],
            "design_page": design_page}


def manifest(ws=None, site_index: list | None = None) -> dict:
    """The whole interface as one document, generated from the code that implements it."""
    from .mcp_server import _tools
    from .service import PAGE_ACTIONS
    from .site_guide import studio_hints
    api = editor_api()
    return {
        "rule": ("You can do what is declared here and nothing else: a page action on an undeclared control, a "
                 "path that is no place, or an undeclared Studio verb is refused, and the refusal lists what is "
                 "declared instead. Read, scroll and highlight work on anything visible."),
        "places": {"workspace": WORKSPACE_PLACES,
                   "website": places(site_index) if site_index else "the site's index could not be read",
                   "also": "any link that is on the page you are on"},
        "controls": {"inline": [{"hint": h["hint"], "name": h["name"], "what": h["what"]} for h in studio_hints()],
                     "forms": DECLARED_FORMS,
                     "out_of_line": OUT_OF_LINE,
                     "by_construction": "links (they go where they point) and native fold-outs (<summary>)"},
        "studio_verbs": {k: v for k, v in api.items() if v["use"] == "agent"},
        "studio_verbs_not_for_agents": sorted(k for k, v in api.items() if v["use"] != "agent"),
        "page_actions": list(PAGE_ACTIONS),
        "tools": [{"name": n, "about": d} for n, d, _ in _tools()],
    }
