"""Generated LogicQ programs: the showcase, written as plain LogicQ text.

A 96-block program is too long to write by hand and too regular to be interesting to
read line by line, so it is generated -- but as `.lq` TEXT, parsed by the same front end
as any hand-written program, never as instruction objects built behind the parser's back.
"""

from __future__ import annotations

from .codes import TUTORIAL_BB

__all__ = ["showcase", "declarations"]


def declarations(blocks: int, code: str = "bb72") -> list[str]:
    l, m, A, B, (n, k, d) = TUTORIAL_BB[code]
    return [f"code q{i} as BivariateBicycle {{ l = {l}; m = {m}; A = {A}; B = {B}; "
            f"params = ({n}, {k}, {d}); }}" for i in range(blocks)]


def showcase(blocks: int, code: str = "bb72") -> str:
    """Entangle every pair, link neighbouring pairs by parity measurements, read out.

    Blocks bind to tiles in row-major order, two to a pair, so `q{2i}` and `q{2i+1}` share
    a transversal-CNOT station and `q{2i+1}`, `q{2i+2}` are neighbours on the messenger bus.
    """
    if blocks % 2:
        raise ValueError("the showcase pairs its blocks; give an even number")
    pairs = blocks // 2
    out = [f"// showcase: {blocks} blocks of {code}, generated by qccd.gadget.programs", ""]
    out += declarations(blocks, code)
    out += ["", "// 1. a logical X on logical 0 of every control block (a Pauli frame update)"]
    out += [f"Logical X q{2 * i}[0]" for i in range(pairs)]
    out += ["", "// 2. a block-level transversal CNOT inside every pair"]
    out += [f"transversalCNOTBatch q{2 * i} q{2 * i + 1}" for i in range(pairs)]
    out += ["", "// 3. link neighbouring pairs: Z̄⊗Z̄ on logical 0, one messenger each"]
    c = 0
    for i in range(pairs - 1):
        out.append(f"ppm c{c} := M q{2 * i + 1}[0]↦Z, q{2 * i + 2}[0]↦Z")
        c += 1
    out += ["", "// 4. the X̄⊗X̄ parity of logical 1 inside every pair"]
    for i in range(pairs):
        out.append(f"ppm c{c} := M q{2 * i}[1]↦X, q{2 * i + 1}[1]↦X")
        c += 1
    out += ["", "// 5. undo the CNOT in every other pair, the Tutorial's way"]
    out += [f"Logical transversalBatch q{2 * i} -> q{2 * i + 1}" for i in range(0, pairs, 2)]
    out += ["", "// 6. a T gate on logical 3 of every fourth block: a messenger takes the injection's",
            "//    Z̄⊗Z_T parity from the block to the row's 15-to-1 factory and back"]
    out += [f"magic T q{j}[3]" for j in range(0, blocks, 4)]
    out += ["", "// 7. read logical 2 of every block in Z"]
    for j in range(blocks):
        out.append(f"Logical measure q{j}[2]↦Z -> c{c}")
        c += 1
    return "\n".join(out) + "\n"
